development:
  adapter: postgresql
  encoding: unicode
  database: kartoteka
  pool: 5
  username: sergei
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: kartoteka
  pool: 5
  username: sergei
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kartoteka
  pool: 5
  username: sergei
  password:

cucumber:
  <<: *TEST