development:
  adapter: postgresql
  encoding: unicode
  database: kartochka_development
  pool: 5
  username: sergei
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: kartochka_test
  pool: 5
  username: sergei
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kartochka_production
  pool: 5
  username: sergei
  password:

cucumber:
  <<: *TEST