development:
  adapter: postgresql
  encoding: unicode
  database: kartochka_development
  pool: 5
  username: sergei
  password:
  port: 5432

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: kartochka_test
  pool: 5
  username: sergei
  password:
  port: 5432
  
production:
  adapter: postgresql
  encoding: unicode
  database: kartochka_production
  pool: 5
  username: sergei
  password:
  port: 5432

cucumber:
  <<: *TEST